# Generated by Django 5.1.6 on 2025-03-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('LINE', 'LINE'), ('Telegram', 'Telegram'), ('Facebook', 'Facebook')], max_length=50)),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('sentiment', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
