# Generated by Django 5.1.6 on 2025-03-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_partner_trainingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='fine_tuned_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='api_key',
            field=models.CharField(default='06de5e9ff7ee49dba15c5f2d0621824d', editable=False, max_length=64, unique=True),
        ),
    ]
